Repository AY2021S1-CS2103T-F13-1/tp, pull requests merged in 2020-10, with the labels that each got.

#39 add constructor and command tests
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/ItemPrecursor.java
  src/main/java/seedu/address/model/location/Location.java
  src/main/java/seedu/address/model/recipe/RecipePrecursor.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRecipeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddRecipeCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddRecipeCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/item/QuantityTest.java
  src/test/java/seedu/address/model/location/LocationTest.java
  src/test/java/seedu/address/model/recipe/ProductQuantityTest.java
  src/test/java/seedu/address/model/recipe/RecipePrecursorTest.java
  src/test/java/seedu/address/model/recipe/RecipeTest.java
  src/test/java/seedu/address/testutil/ItemBuilder.java
  src/test/java/seedu/address/testutil/ItemListBuilder.java
  src/test/java/seedu/address/testutil/ItemPrecursorBuilder.java
  src/test/java/seedu/address/testutil/LocationListBuilder.java
  src/test/java/seedu/address/testutil/RecipeBuilder.java
  src/test/java/seedu/address/testutil/RecipeListBuilder.java
  src/test/java/seedu/address/testutil/RecipePrecursorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIngredientPrecursors.java
  src/test/java/seedu/address/testutil/TypicalItemPrecursors.java
  src/test/java/seedu/address/testutil/TypicalItems.java
  src/test/java/seedu/address/testutil/TypicalRecipePrecursors.java
Labels: type.Task

#40 Remove item command.
  build/resources/main/view/HelpWindow.fxml
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecipeCommand.java
  src/main/java/seedu/address/logic/parser/DeleteItemCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/model/ItemList.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/UniqueItemList.java
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/model/recipe/UniqueRecipeList.java
  src/main/java/seedu/address/ui/InventoryListPanel.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteItemCommandParserTest.java
  src/test/java/seedu/address/model/ItemListTest.java
  src/test/java/seedu/address/model/item/ItemTest.java
  src/test/java/seedu/address/model/item/UniqueItemListTest.java
  src/test/java/seedu/address/model/recipe/IngredientTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: feature.Item, type.Story

#44 add command to view details of an item
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewDetailsCommand.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/logic/parser/ViewDetailsCommandParser.java
  src/main/java/seedu/address/model/item/NameIsExactlyPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InventoryDetailedCard.java
  src/main/java/seedu/address/ui/InventoryListPanel.java
  src/main/java/seedu/address/ui/InventoryMainWindow.java
  src/main/resources/view/InventoryListDetailedCard.fxml
  src/main/resources/view/InventoryMainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewDetailsCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewDetailedCommandParserTest.java
Labels: feature.Item

#47 View recipe
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecipeCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListItemCommand.java
  src/main/java/seedu/address/logic/commands/ListRecipeCommand.java
  src/main/java/seedu/address/logic/commands/ViewDetailsCommand.java
  src/main/java/seedu/address/logic/parser/InventoryListParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/logic/parser/ListItemCommandParser.java
  src/main/java/seedu/address/logic/parser/ListRecipeCommandParser.java
  src/main/java/seedu/address/model/InventoryComponent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/DetailedItem.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/NameIsExactlyPredicate.java
  src/main/java/seedu/address/model/recipe/Ingredient.java
  src/main/java/seedu/address/model/recipe/IngredientList.java
  src/main/java/seedu/address/model/recipe/PrintableRecipe.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/ui/DetailedItemCard.java
  src/main/java/seedu/address/ui/DisplayedInventoryType.java
  src/main/java/seedu/address/ui/InventoryListPanel.java
  src/main/java/seedu/address/ui/InventoryMainWindow.java
  src/main/java/seedu/address/ui/RecipeCard.java
  src/main/resources/view/RecipeCard.fxml
  src/test/java/seedu/address/logic/commands/AddItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddRecipeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRecipeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteRecipeCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ListItemCommandTest.java
  src/test/java/seedu/address/logic/commands/ListRecipeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ListRecipeCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewDetailsCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRecipeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListRecipeCommandParserTest.java
  src/test/java/seedu/address/model/recipe/IngredientTest.java
  src/test/java/seedu/address/model/recipe/PrintableRecipeTest.java
Labels: feature.Recipe

#42 Find Items feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindItemCommand.java
  src/main/java/seedu/address/logic/parser/FindItemCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/model/item/NameMatchesKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindItemCommandTest.java
  src/test/java/seedu/address/logic/parser/FindItemCommandParserTest.java
  src/test/java/seedu/address/model/item/NameMatchesKeywordsPredicateTest.java
Labels: feature.Item

#53 Edit item
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/main/java/seedu/address/logic/parser/EditItemCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteRecipeCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EditItemCommandTest.java
  src/test/java/seedu/address/logic/commands/FindItemCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewDetailsCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditItemCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: feature.Item

#72 update DG - jinglin
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/sequenceDiagrams/AddQuantityToItemCommandSequenceDiagram.puml
  docs/images/AddQuantityToItemCommandSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: priority.High, type.Documentation

#74 Update dg kh
  docs/CommandSequenceDiagram.md
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/AddItemSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/AddQuantityToItemCommandSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/AddRecipeSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/AddSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/DeleteItemSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/DeleteRecipeSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/ListItemSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/ListRecipeSequenceDiagram.puml
  docs/images/AddQuantityToItemCommandSequenceDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/commandseqdiagrams/AddItemSequenceDiagram.png
  docs/images/commandseqdiagrams/AddSequenceDiagram.png
  docs/images/commandseqdiagrams/DeleteItemSequenceDiagram.png
  docs/images/commandseqdiagrams/DeleteRecipeSequenceDiagram.png
  docs/images/commandseqdiagrams/ListItemSequenceDiagram.png
  docs/images/commandseqdiagrams/ListRecipeSequenceDiagram.png
  src/main/java/seedu/address/ui/InventoryListPanel.java
Labels: type.Documentation

#78 Optionals for additem and quick bug fix
  docs/UserGuide.md
  docs/diagrams/sequenceDiagrams/DeleteItemSequenceDiagram.puml
  docs/images/commandseqdiagrams/DeleteItemSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditItemCommandParser.java
  src/main/java/seedu/address/logic/parser/ItemParserUtil.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/location/UniqueLocationList.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonSerializableItemList.java
  src/main/java/seedu/address/storage/JsonSerializableRecipeList.java
  src/main/java/seedu/address/ui/DetailedItemCard.java
  src/main/java/seedu/address/ui/InventoryCard.java
  src/main/resources/view/InventoryListCard.fxml
  src/main/resources/view/InventoryListDetailedCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandTest.java
  src/test/java/seedu/address/logic/commands/EditItemCommandTest.java
  src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRecipeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ItemParserUtilTest.java
  src/test/java/seedu/address/model/item/ItemTest.java
  src/test/java/seedu/address/model/location/UniqueLocationListTest.java
  src/test/java/seedu/address/model/recipe/RecipeTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/ItemBuilder.java
  src/test/java/seedu/address/testutil/ItemPrecursorBuilder.java
  src/test/java/seedu/address/testutil/TypicalItemPrecursors.java
  src/test/java/seedu/address/testutil/TypicalItems.java
  src/test/java/seedu/address/testutil/TypicalLocations.java
  src/test/java/seedu/address/testutil/TypicalTags.java
Labels: Need Help

#81 Enable craft item feature
  docs/images/commandseqdiagrams/ListRecipeSequenceDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddQuantityToItemCommand.java
  src/main/java/seedu/address/logic/commands/ClearRecipeCommand.java
  src/main/java/seedu/address/logic/commands/CraftItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecipeCommand.java
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/main/java/seedu/address/logic/commands/ListItemCommand.java
  src/main/java/seedu/address/logic/commands/ListRecipeCommand.java
  src/main/java/seedu/address/logic/commands/ViewDetailsCommand.java
  src/main/java/seedu/address/logic/parser/CraftItemCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/logic/parser/ItemParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/Quantity.java
  src/main/java/seedu/address/ui/InventoryMainWindow.java
  src/test/java/seedu/address/logic/commands/CraftItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CraftItemCommandTest.java
  src/test/java/seedu/address/logic/parser/CraftItemCommandParserTest.java
  src/test/java/seedu/address/model/item/ItemTest.java
Labels: feature.Item

#84 add undo/redo functionality
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/commands/AddQuantityToItemCommand.java
  src/main/java/seedu/address/logic/commands/AddRecipeCommand.java
  src/main/java/seedu/address/logic/commands/ClearItemCommand.java
  src/main/java/seedu/address/logic/commands/ClearRecipeCommand.java
  src/main/java/seedu/address/logic/commands/CraftItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecipeCommand.java
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/model/Inventory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedInventory.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
Labels: type.Story

#90 Add tests
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/ItemList.java
  src/main/java/seedu/address/model/item/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/item/NameMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/recipe/IngredientList.java
  src/test/java/seedu/address/logic/commands/FindItemCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/item/DetailedItemTest.java
  src/test/java/seedu/address/model/item/ItemPrecursorTest.java
  src/test/java/seedu/address/model/item/NameIsExactlyPredicateTest.java
  src/test/java/seedu/address/model/item/NameMatchesKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/UniqueItemListTest.java
  src/test/java/seedu/address/model/location/UniqueLocationListTest.java
  src/test/java/seedu/address/model/recipe/IngredientListTest.java
  src/test/java/seedu/address/model/recipe/PrintableRecipeTest.java
  src/test/java/seedu/address/model/util/SampleDataTest.java
Labels: priority.Medium, type.Task

#95 Fixed bug with addtag command and added unittests in response
  src/main/java/seedu/address/logic/commands/AddItemTagCommand.java
  src/test/java/seedu/address/logic/commands/AddItemTagCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddItemTagCommandTest.java
Labels: type.Bug

#91 Add check craft command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddItemTagCommand.java
  src/main/java/seedu/address/logic/commands/AddQuantityToItemCommand.java
  src/main/java/seedu/address/logic/commands/CheckCraftCommand.java
  src/main/java/seedu/address/logic/commands/CraftItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecipeCommand.java
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/main/java/seedu/address/logic/parser/CheckCraftCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/test/java/seedu/address/logic/commands/CheckCraftCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckCraftCommandTest.java
  src/test/java/seedu/address/logic/commands/CraftItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CraftItemCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteItemCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRecipeCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteRecipeCommandTest.java
  src/test/java/seedu/address/logic/parser/CheckCraftCommandParserTest.java
Labels: feature.Item, feature.Recipe, priority.Low

#98 Fix bug in crafting and clear item
  src/main/java/seedu/address/logic/commands/CheckCraftCommand.java
  src/main/java/seedu/address/logic/commands/ClearItemCommand.java
  src/main/java/seedu/address/logic/commands/CraftItemCommand.java
  src/test/java/seedu/address/logic/commands/CheckCraftCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckCraftCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearItemCommandTest.java
  src/test/java/seedu/address/logic/commands/CraftItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/FindByTagCommandTest.java
  src/test/java/seedu/address/logic/parser/EditItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ItemParserUtilTest.java
Labels: severity.High, type.Bug

#99 update UG for PE-D
  docs/UserGuide.md
Labels: type.Documentation

#100 Update UG
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation
