Repository AY2021S1-CS2103T-F13-1/tp, pull requests merged in 2020-11, with the labels that each got.

#144 update error message for AddQuantityToItemCommand
  src/main/java/seedu/address/logic/commands/AddQuantityToItemCommand.java
Labels: type.Bug

#141 Craft undo bugfix
  src/main/java/seedu/address/logic/commands/AddQuantityToItemCommand.java
  src/main/java/seedu/address/logic/commands/CraftItemCommand.java
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
  src/test/java/seedu/address/logic/commands/AddQuantityToItemCommandTest.java
  src/test/java/seedu/address/logic/commands/EditItemCommandTest.java
Labels: severity.Medium, type.Bug

#142 fix quantity, craft command, and help window
  src/main/java/seedu/address/logic/commands/AddQuantityToItemCommand.java
  src/main/java/seedu/address/logic/commands/CraftItemCommand.java
  src/main/java/seedu/address/logic/parser/AddQuantityToItemCommandParser.java
  src/main/java/seedu/address/logic/parser/CraftItemCommandParser.java
  src/main/java/seedu/address/logic/parser/ItemParserUtil.java
  src/main/java/seedu/address/model/item/Quantity.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddQuantityToItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddQuantityToItemCommandTest.java
  src/test/java/seedu/address/logic/commands/CraftItemCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AddQuantityToItemCommandParserTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#147 update UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Documentation

#155 View update
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewDetailsCommand.java
  src/main/java/seedu/address/model/InventoryComponent.java
  src/main/java/seedu/address/model/item/NameIsExactlyPredicate.java
  src/main/java/seedu/address/model/recipe/PrintableRecipe.java
  src/main/java/seedu/address/ui/InventoryListPanel.java
  src/main/java/seedu/address/ui/RecipeCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ViewDetailsCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ViewDetailsCommandTest.java
  src/test/java/seedu/address/model/item/NameIsExactlyPredicateTest.java
Labels: priority.Medium

#157 update undo/redo dg documentation
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
Labels: type.Documentation

#158 UG pictures
  docs/UserGuide.md
  docs/images/UG images/UG addi.png
  docs/images/UG images/UG addq.png
  docs/images/UG images/UG addr.png
  docs/images/UG images/UG addt.png
  docs/images/UG images/UG check.png
  docs/images/UG images/UG cleari.png
  docs/images/UG images/UG clearr.png
  docs/images/UG images/UG craft.png
  docs/images/UG images/UG deli.png
  docs/images/UG images/UG delr.png
  docs/images/UG images/UG edit.png
  docs/images/UG images/UG find.png
  docs/images/UG images/UG findt.png
  docs/images/UG images/UG listi.png
  docs/images/UG images/UG listr.png
  docs/images/UG images/UG redo.png
  docs/images/UG images/UG undo.png
  docs/images/UG images/UG view.png
Labels: type.Documentation

#154 added PPP
  docs/AboutUs.md
  docs/team/aqcd.md
  docs/team/shijinglin.md
Labels: type.Documentation

#161 Ppp
  docs/AboutUs.md
  docs/team/justacasul.md
  docs/team/liuzhengdao.md
Labels: type.Documentation

#165 Dg kh update
  docs/DeveloperGuide.md
  docs/diagrams/sequenceDiagrams/ListItemSequenceDiagram.puml
  docs/diagrams/sequenceDiagrams/ListRecipeSequenceDiagram.puml
  docs/images/commandseqdiagrams/ListItemSequenceDiagram.png
  docs/images/commandseqdiagrams/ListRecipeSequenceDiagram.png
Labels: type.Documentation

#166 Qacode
  docs/DeveloperGuide.md
  docs/Usecases.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/team/stephentan.md
  src/main/java/seedu/address/logic/commands/DeleteItemCommand.java
  src/main/java/seedu/address/logic/parser/FindItemCommandParser.java
  src/main/java/seedu/address/model/item/NameIsExactlyPredicate.java
  src/main/java/seedu/address/model/item/NameMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/item/TagMatchesKeywordsPredicate.java
  src/test/java/seedu/address/model/item/NameIsExactlyPredicateTest.java
  src/test/java/seedu/address/model/item/NameMatchesKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/TagMatchesKeywordsPredicateTest.java
Labels: type.Documentation, type.Task

#167 ppp Kheng Hun
  docs/team/khenghun.md
  docs/team/siewkhenghun.md
Labels: type.Documentation

#176 fix error message
  src/main/java/seedu/address/logic/commands/EditItemCommand.java
Labels: severity.Low

#178 Ug fix
  docs/UserGuide.md
Labels: type.Documentation

#179 Add my PPP; fix duplicate recipe bug
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelSubClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/ModelSubClassDiagram.png
  docs/team/khenghun.md
  docs/team/rahul.md
  docs/team/rahul0506.md
  src/main/java/seedu/address/logic/commands/FindItemCommand.java
  src/main/java/seedu/address/logic/parser/RecipeParserUtil.java
  src/main/java/seedu/address/model/recipe/IngredientList.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/test/java/seedu/address/model/recipe/RecipeTest.java
Labels: type.Bug, type.Documentation
