Repository AY2021S1-CS2103T-F13-1/tp, pull requests merged in 2020-09, with the labels that each got.

#21 Add tests
  src/main/java/seedu/address/model/location/Location.java
  src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InvParserUtilTest.java
  src/test/java/seedu/address/model/item/QuantityTest.java
  src/test/java/seedu/address/model/item/UniqueItemListTest.java
Labels: priority.low

#24 fix checkstyle errors
  build/resources/main/view/DarkTheme.css
  build/resources/main/view/HelpWindow.fxml
  src/main/java/seedu/address/logic/parser/RecipeParserUtil.java
  src/main/java/seedu/address/model/item/ItemPrecursor.java
  src/main/java/seedu/address/model/item/UniqueItemList.java
  src/main/java/seedu/address/model/recipe/RecipePrecursor.java
  src/main/java/seedu/address/storage/JsonAdaptedIngredient.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/InventoryListCard.fxml
  src/main/resources/view/InventoryListPanel.fxml
  src/main/resources/view/InventoryMainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/InvParserUtilTest.java
Labels: priority.high

#27 Delete recipe
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/commands/AddRecipeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecipeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteRecipeCommandParser.java
  src/main/java/seedu/address/logic/parser/InventoryParser.java
  src/main/java/seedu/address/logic/parser/RecipeParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecipeList.java
  src/main/java/seedu/address/model/recipe/Recipe.java
  src/main/java/seedu/address/model/recipe/UniqueRecipeList.java
Labels: feature.recipe, type.story
